FILTER_REGEX_EXCLUDE: (\/test\/|\/lib\/)
DISABLE:
  - COPYPASTE
  - EDITORCONFIG
  - TYPESCRIPT # sfdx-essentials use deprecated tslint, reactivate TYPESCRIPT after migration to eslint
FILEIO_REPORTER: true
