site_name: sfdx-essentials
site_url: https://nvuillam.github.io/sfdx-essentials
repo_url: https://github.com/nvuillam/sfdx-essentials
edit_uri: tree/master/docs
site_author: Nicolas Vuillamy
site_description: Salesforce DX Plugin by Hardis Group.
copyright: >-
  Copyright &copy; 2021 <a href="https://github.com/nvuillam">Nicolas
  Vuillamy</a>
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant
  logo: assets/images/salesforce-logo.png
  favicon: assets/images/salesforce-icon.png
  palette:
    primary: light blue
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - mdx_truly_sane_lists
  - attr_list
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
  - javascripts/gtag.js
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/regular/question-circle
      link: https://github.com/nvuillam/sfdx-essentials/issues
      title: Need help ? Post an issue :)
    - icon: fontawesome/brands/github
      link: https://github.com/nvuillam/sfdx-essentials
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/nvuillam/sfdx-hardis
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/NicolasVuillamy
  generator: false
nav:
  - Home: index.md
  - Commands:
      essentials:
        metadata:
          filter-from-packagexml: essentials/metadata/filter-from-packagexml.md
          filter-xml-content: essentials/metadata/filter-xml-content.md
          uncomment: essentials/metadata/uncomment.md
        mig:
          add-namespace: essentials/mig/add-namespace.md
          fix-aura-attributes-names: essentials/mig/fix-aura-attributes-names.md
          migrate-object-model: essentials/mig/migrate-object-model.md
        packagexml:
          append: essentials/packagexml/append.md
          remove: essentials/packagexml/remove.md
          sort: essentials/packagexml/sort.md
        permissionset:
          generate: essentials/permissionset/generate.md
        project:
          change-dependency-version: essentials/project/change-dependency-version.md
          check-consistency-with-packagexml: essentials/project/check-consistency-with-packagexml.md
          count-apex-lines: essentials/project/count-apex-lines.md
  - License: license.md
  - Changelog: CHANGELOG.md
